### ISSUE TITLE
ScsHttpHandler no longer available

### ISSUE THREAD

**Issue by Ldaco** [JeffDarchuk/SitecoreSidekick#23]
In our use of Sidekick I've found a JobViewerHandler that has been in place but won't build after the upgrade to 1.4.2:

public class JobViewerHandler : ScsHttpHandler

I see that there are three handlers here, including the ScsHttpHandler:
https://github.com/JeffDarchuk/SitecoreSidekick/tree/master/Source/SitecoreSidekick/Handlers

However the SCSHttpHandler isn't included in the classes to compile in the csproj file:
https://github.com/JeffDarchuk/SitecoreSidekick/blob/master/Source/SitecoreSidekick/SitecoreSidekick.csproj

Was this by design or just an oversight and needs the csproj file updated?  If by design, is there any info on how to get it working in the new version?

**Comment by JeffDarchuk** [comment]
That is by design, a smallish migration is needed in order to move an older style sidekick app to the newest version.  I've gotten asked this enough times that I made a migration guide:
[Migration Guide](https://jeffdarchuk.com/2017/11/19/migrating-sidekick-app-1-1-2-to-1-4/)

Long story short it's to take advantage of security features of MVC and to close possible security holes of having a custom http handler.
